ecom/accounts/urls.py
from django.urls import path
from  . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),

]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('accounts/', include('accounts.urls')),
] 
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/store/urls.py
from django.urls import path
from . import views
from .views import HomePage, Cart, Checkout, OrderDetails
app_name = 'store'
urlpatterns = [
    path('', HomePage.as_view(), name = "home"),
    path('products/<slug:slug>/', views.productDetail, name = "product_detail"),
    path('cart/', Cart.as_view(), name = "cart"),
    path('checkout',Checkout.as_view(), name = "checkout"),  
    path('orders/',OrderDetails.as_view(), name = 'order') ,
    
    
]

ecom/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.aggregates import Max
from django.db.models.deletion import CASCADE, SET_DEFAULT
from django.db.models.fields import DateField, DateTimeField, SlugField
from django.db.models.fields.related import ForeignKey
# Create your models here.
class Customer(models.Model):
    user_id = models.CharField(max_length=1000, default= None)
    first_name = models.CharField(max_length=200, null =True)
    last_name = models.CharField(max_length=200, null =True)
    phone = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=200, null= True)


    def __str__(self):
        return str(self.id)

    def save_customer_details(self):
        self.save()

    @staticmethod
    def get_customer_id(user_id):
        return Customer.objects.filter(id__in = user_id)

    @staticmethod
    def get_customerId_by_email(email):
        return Customer.objects.get(email=email)



  






class Category(models.Model):
    category_name = models.CharField(max_length=255, null= False)
    slug = models.SlugField(max_length=255, null= False)
    image = models.ImageField(upload_to = 'uploads/category/', null = True, blank = True)

    class Meta:
        verbose_name_plural = 'Categories'


    @staticmethod
    def get_all_categories():
        return Category.objects.all()


    def __str__(self):
        return self.category_name


class Product(models.Model):
    
    category = models.ForeignKey(Category, null = True, blank= True,related_name= 'products', on_delete= models.CASCADE)
    name = models.CharField(max_length=255, null=True)
    slug = models.SlugField(max_length=255, null= True)
    price = models.FloatField( null=True)
    image = models.ImageField( null = True, blank= True)
    description = models.CharField(max_length = 200, null = True)
    date_created = models.DateTimeField(auto_now_add = True, null = True)

    @staticmethod
    def get_all_products():
        return Product.objects.all()


    @staticmethod
    def get_product_by_id(product_id):
        return Product.objects.filter(id__in = product_id)
        


    @staticmethod
    def get_products_by_categoryId(category_id):
        if category_id:
            return Product.objects.filter(category = category_id)
        else:
            return Product.get_all_products()
 
    
    def __str__(self):
        return self.name


class ProductVariationOption(models.Model):
    SIZE = (
        ('Small','S'),
        ('Large','L'),
        ('Extra Large', 'XL'),
        ('Double Extra large', 'XXL'),
    )
    COLOUR = (
        ('Black', 'Black'),
        ('Red', 'Red'),
        ('Blue', 'Blue'),
    )
    product = models.ForeignKey(Product, null = True, blank= True,related_name= 'products', on_delete= models.CASCADE)
    size = models.CharField(max_length=200, null=True, choices = SIZE)
    colour = models.CharField(max_length=200, null=True, choices=COLOUR)



    def __str__(self):
        return str(self.id)


    @staticmethod
    def get_products_by_id(product_id):
        return ProductVariationOption.objects.filter(id__in = product_id)



class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    adress = models.CharField(max_length=300, null =False)
    city = models.CharField(max_length=100, null =False)
    state = models.CharField(max_length=100, null =False)
    counrty = models.CharField(max_length=100, null =False)
    pin_code = models.CharField(max_length=50, null =False)

    def __str__(self):
        return str(self.adress)

    @staticmethod
    def get_address_by_customerId(customer):
        return ShippingAddress.objects.get(customer = customer)
    
    def save_address_details(self):
        self.save()


class Order(models.Model):
    STATUS = (
			('Pending', 'Pending'),
			('Out for delivery', 'Out for delivery'),
			('Delivered', 'Delivered'),
			)
    customer = models.ForeignKey(Customer, null = True, blank = True, on_delete = models.SET_NULL)
    product = models.ForeignKey(Product, null = True, blank = True, on_delete = models.SET_NULL)
    shipping_address = models.ForeignKey(ShippingAddress, null = True, blank = True, on_delete = models.SET_NULL)
    price = models.FloatField(null=True)
    quantity = models.IntegerField(default=1)
    ordered_date = models.DateTimeField(auto_now_add = True)
    status = models.CharField(max_length=200, null=True, choices=STATUS, default= 'Pending')

    def __str__(self):
        return str(self.id)

    @staticmethod
    def get_orders_by_customerId(customer):
        return Order.objects.filter(customer=customer)

    def placeOrder(self):
        self.save()

    

ecom/store/views.py
from django.http import request
from django.shortcuts import get_object_or_404, render, redirect
from django.template import context
from .models import *
from django.views import View
# Create your views here.
class HomePage(View):
    def post(self, request):
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')

        if cart:
            quantity = cart.get(product)
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(product)
                    else:    
                        cart[product] = quantity-1
                else:
                    cart[product] = quantity + 1
            else:
                cart[product] = 1 
        else:
            cart = {}
            cart[product] = 1

        request.session['cart'] = cart

        
        return redirect('store:home')
    def get(self, request):
        products = None
        cart = request.session.get('cart')
        uid = request.session.get('uId')
        print(uid)
        if not cart:    
            request.session['cart'] = {}
        categories = Category.get_all_categories()
        categoryID = request.GET.get('category')
        if categoryID:
            products = Product.get_products_by_categoryId(categoryID)


        else:
            products = Product.get_all_products()

        context = {'products': products,
                'categories': categories,
                }

        return render(request, 'store/home.html', context)




def productDetail(request, slug):
    products = get_object_or_404(Product, slug=slug)
    context = {'products': products}
    return render(request, 'store/details.html', context)


def categoryDetail(request, category_id):
    categories = Category.get_all_categories()
    products = Product.objects.get(category_id)
    context = {'categories': categories,
               'products': products}
    return render(request, 'store/categories_detail.html', context)


class Cart(View):
    def post(self,request):
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')

        if cart:
            quantity = cart.get(product)
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(product)
                    else:    
                        cart[product] = quantity-1
                else:
                    cart[product] = quantity + 1
            else:
                cart[product] = 1 
        else:
            cart = {}
            cart[product] = 1

        request.session['cart'] = cart
        print('cart',request.session['cart'])
        return redirect('store:cart')
    def get(self, request):
        product_id = list(request.session.get('cart').keys())
        products = ProductVariationOption.get_products_by_id(product_id) 
        items = ProductVariationOption.get_products_by_id(product_id)    
        context = {'products':products, 'items':items}
        return render(request, 'store/cart.html', context)



class Checkout(View):
    def post(self, request):
        
        cart = request.session.get('cart')
        products = Product.get_product_by_id(list(cart.keys()))
        customer = request.session.get('customer')
        print("hello:",customer)
        for product in products:
            order = Order(customer = Customer(id=customer), product = product, 
                    shipping_address = ShippingAddress.get_address_by_customerId(customer),
                    price = product.price, quantity = cart.get(str(product.id)))
            order.placeOrder()

        request.session['cart'] = {}

        return redirect('store:cart')
  
    
class OrderDetails(View):
    def get(self,request):
        customer = request.session.get('customer')
        orders = Order.get_orders_by_customerId(customer)
        context = {'orders': orders}
        return render(request, 'store/orders.html', context)

ecom/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% load cartfilter %}
{% block content %}
<div>
   
<!--Section: Block Content-->
<section>
    <div class="container-fluid">
        <!--Grid row-->
        <div class="row">
    
        <!--Grid column-->
        <div class="col-lg-8">
    
            <!-- Card -->
            <div class="mb-3">
            <div class="pt-4 wish-list">
    
                <h5 class="mb-4">Cart (<span>2</span> items)</h5>
                {% for item in items %}
                <div class="row mb-4">
                    <div class="col-md-5 col-lg-3 col-xl-3">
                        <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                        <img class="img-fluid w-110"
                            src="{{item.product.image.url}}" alt="Sample">
                        </div>
                    </div>
                    <div class="col-md-7 col-lg-9 col-xl-9">
                        <div>
                        <div class="d-flex justify-content-between">
                            <div>
                            <h5>{{item.product.name}}</h5>
                                <p class="mb-2 text-muted text-uppercase small">Quantity:{{item.product|quantity_count:request.session.cart}}</p> 
                                <p class="mb-2 text-muted text-uppercase small">Colour:{{item.colour}}</p>
                                <p class="mb-3 text-muted text-uppercase small">Size:{{item.size}}</p>
                            </div>
                            <div>
                                <div class="def-number-input number-input safari_only mb-0 w-100">
                                    <div class="cart-footer p0">
                                        {% if item.product|is_in_cart:request.session.cart %}
                                            <div>
                                                <form action="" method="POST" class="col-2">
                                                    {% csrf_token %}
                                                    <input hidden type="text" name='product' value='{{item.product.id}}'>
                                                    <input hidden type="text" name='remove' value='True'>
                                                    <input type="submit" value=" - " class= "btn btn-block btn-secondary">
                                                </form>
                                                <div class="text-center col">{{item.product|quantity_count:request.session.cart}}</div>
                                                <form action="" method="POST" class="col-2">
                                                    {% csrf_token %}
                                                    <input hidden type="text" name='product' value='{{item.product.id}}'>
                                                    <input type="submit" value=" + " class="btn btn-block btn-secondary">
                                                </form>
            
                                            </div>
                                        {% else %}
                                            <form action="cart/#{{product.id}}" method = "POST" class="btn-block">
                                                {% csrf_token %}
                                                <input hidden type="text" name='product' value='{{item.product.id}}'>
                                                <button type="submit" class="float-right btn btn-light border form-control" >Add to Cart</button> 
                                                
                                            </form>
                                        {% endif %}
    
    
                                    </div>
                                    
                                </div>
                                <small id="passwordHelpBlock" class="form-text text-muted text-center">
                                
                                </small>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <a href="#!" type="button" class="card-link-secondary small text-uppercase mr-3"><i
                                    class="fas fa-trash-alt mr-1"></i> Remove item </a>
                                <a href="#!" type="button" class="card-link-secondary small text-uppercase"><i
                                    class="fas fa-heart mr-1"></i> Move to wish list </a>
                            </div>
                            <p class="mb-0"><span><strong id="summary">{{item.product.price}}</strong></span></p class="mb-0">
                        </div>
                        </div>
                    </div>
                </div>
                {% endfor%}
                

                <p class="text-primary mb-0"><i class="fas fa-info-circle mr-1"></i> Do not delay the purchase, adding
                items to your cart does not mean booking them.</p>
    
            </div>
            </div>
            <!-- Card -->
    
            <!-- Card -->
            <div class="mb-3">
            <div class="pt-4">
    
                <h5 class="mb-4">Expected shipping delivery</h5>
    
                <p class="mb-0"> Thu., 12.03. - Mon., 16.03.</p>
            </div>
            </div>
            <!-- Card -->
    
            <!-- Card -->
            <div class="mb-3">
            <div class="pt-4">
    
                <h5 class="mb-4">We accept</h5>
    
                <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                alt="Visa">
                <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                alt="American Express">
                <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                alt="Mastercard">
                <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
                alt="PayPal acceptance mark">
            </div>
            </div>
            <!-- Card -->
    
        </div>
        <!--Grid column-->
    
        <!--Grid column-->
        <div class="col-lg-4">
    
            
            <div class="mb-3">
            <div class="pt-4">
    
                <h5 class="mb-3">The total amount of</h5>
    
                <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                    Temporary amount
                    <span>$25.98</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                    Shipping
                    <span>Gratis</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                    <div>
                    <strong>The total amount of</strong>
                    <strong>
                        <p class="mb-0">(including GST)</p>
                    </strong>
                    </div>
                    <span><strong>{{products|total_cart_price:request.session.cart}}</strong></span>
                </li>
                </ul>
    
                
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-outline-info btn-md btn-rounded btn-navbar waves-effect waves-light" 
                    data-toggle="modal" data-target="#exampleModal">
                    Checkout
                </button>
                
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Checkout</h5>
                        <hr>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            <div>
                                <class class="m-2 p-2">
                                    <form action = "/checkout" method="POST">
                                        {% csrf_token %}
                                        <h3>Are you sure?</h3>
                                          <input type="submit" class = "btn float-right btn-outline-info btn-md btn-rounded btn-navbar waves-effect waves-light" 
                                            value="checkout">
                                    </form>
                                </class>
                            </div>
                        </div>  
                        
                    </div>
                    </div>
                </div>
                
    
            </div>
            </div>
            <!-- Card -->
    
            <!-- Card -->
            
    
        </div>
        <!--Grid column-->
    
        </div>
        <!-- Grid row -->
    </div>
</section>
  <!--Section: Block Content-->


{% endblock content %}

ecom/store/templates/store/checkout.html
{% extends 'store/main.html'%}
{%load static %}

{% block content %}
    
{% endblock content%}

ecom/store/templates/store/details.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <h1 class = "title">{{products.name}}</h1class></h1>
    <img class = "thumbnail" src = "{{products.image.url}}">
    <h3 class="price">Price: {{products.price}}</h3>
    <h3 class="description">Description: {{products.description}}</h3>
    <h3 class="date_created">Date Ordered: {{products.date_created}}</h3>

{% endblock %}

ecom/store/templates/store/home.html
{% extends 'store/main.html' %}
{% load static %}
{% load cartfilter %}
{% block content %}
    <div id="myCarousel" class="carousel slide" data-ride = "carousel">
        <ol class= "carousel-indicators">
            <li data-target="#myCarousel" data-slide-to = "0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to = "1"></li>
            <li data-target="#myCarousel" data-slide-to = "2"></li>
        </ol>
        <div class="carousel-inner" >
            <div class="carousel-item active">
                <div class="overlay-image-1"></div>
                <div class="container">
                    <h1>Example</h1>
                    <p>Hello</p>
                    <a href = "#" class="btn btn-lg btn-primary">Sign Up</a>
                </div>
            </div>
            <div class="carousel-item">
                <div class="overlay-image-2"></div>
                <div class="container">
                    <h1>Slide2</h1>
                    <p>Hello</p>
                    <a href = "#" class="btn btn-lg btn-primary">Sign Up</a>
                </div>
            </div>
            <div class="carousel-item">
                <div class="overlay-image-3"></div>
                <div class="container">
                    <h1>Slide3</h1>
                    <p>Hello</p>
                    <a href = "#" class="btn btn-lg btn-primary">Sign Up</a>
                </div>
            </div>
        </div>
        <a href="#myCarousel" class="carousel-control-prev"
            role="button" data-slide = "prev">
        <span class="sr-only">Previous</span>
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>
        <a href="#myCarousel" class="carousel-control-next"
            role="button" data-slide = "next">
        <span class="sr-only">Next</span>
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
    </div>
    <!--
        
    -->
    
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-lg-3 mx-auto">
                
                <div class="list-group">
                    <a href="/" class="list-group-item list-group-item-action">All Products</a>

                    {% for category in categories %}
                    <a href="/?category={{category.id}}" class="list-group-item">{{category.category_name}}</a>
                    {% endfor %}
                </div>
            </div>
            <div  id='products' class="col-lg-9 mx-auto">
                    <div class="container-fluid">
                        <div class="row mx-auto">
                            {% for product in products %}
                            <div class="col-lg-4 col-6" id={{product.id}}>
                                <img class="thumbnail" src="{{product.image.url}}">
                                <div class="box-element product">
                                    <h6><strong>{{product.name}}</strong></h6>
                                    <hr>
                                    <!-- {{product | is_in_cart:request.session.cart}} -->
                                    <a class="btn btn-outline-success" href="{% url 'store:product_detail' product.id%}">View</a>
                                    <h4 style="display: inline-block; float: right"><strong>INR{{product.price}}</strong></h4>
            
                                </div>
                                <div class="cart-footer p0">
                                    {% if product|is_in_cart:request.session.cart %}
                                        <div class="row no-gutters" >
                                            <form action="/#{{product.id}}" method="POST" class="col-2">
                                                {% csrf_token %}
                                                <input hidden type="text" name='product' value='{{product.id}}'>
                                                <input hidden type="text" name='remove' value='True'>
                                                <input type="submit" value=" - " class= "btn btn-block btn-secondary">
                                            </form>
                                            <div class="text-center col">{{product|quantity_count:request.session.cart}}</div>
                                            <form action="/#{{product.id}}" method="POST" class="col-2">
                                                {% csrf_token %}
                                                <input hidden type="text" name='product' value='{{product.id}}'>
                                                <input type="submit" value=" + " class="btn btn-block btn-secondary">
                                            </form>
        
                                        </div>
                                    {% else %}
                                        <form action="/#{{product.id}}" method = "POST" class="btn-block">
                                            {% csrf_token %}
                                            <input hidden type="text" name='product' value='{{product.id}}'>
                                            <button type="submit" class="float-right btn btn-light border form-control" >Add to Cart</button> 
                                            
                                        </form>
                                    {% endif %}


                                </div>

                                

                            </div>
                            {% endfor %}
                        </div>
                    </div>

            </div>
        </div>
    </div>

{% endblock %}

ecom/store/templates/store/main.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>ECOM</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
                crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
        
        
    </head>
    <body>
        {% include 'store/navbar.html'%}
        
        {% block content%}
        
        
        
        {% endblock %}
        </div>
        <hr>

    </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
         integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
                crossorigin="anonymous"></script>
</html>
</html>

ecom/store/templates/store/navbar.html
{% load static %}



<nav class="navbar navbar-expand-md navbar-light bg-light">

  <a class="navbar-brand" href="{% url 'store:home' %}">
    <img src="{% static 'images/elogo.png'%}" height="60" alt="elogo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link waves-effect" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect" href="#">Contacts</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          {% for category in categories %}
          <a class="dropdown-item" href="/?category={{category.id}}">{{category.category_name}}</a>
          {% endfor %}
        </div>
      </li>
    </ul>
    
    <!-- Right -->
    <ul class="navbar-nav ml-auto">
      <ul class="navbar-nav ml-auto">
  
        <li class="nav-item" style = "margin-left: 10px"> 
          <a href = "{% url 'store:cart' %}" class="btn btn-warning">Cart</a>
    
        </li> 
        {%if request.session.uid %}
          <li class="nav-item">
            <a href="{% url 'store:order'%}" class="nav-link waves-effect">
              Orders
            </a>
          </li>
  
          
      
      
      <tb></tb>
      <tb></tb>
      <li class="nav-item pl-2 mb-2 mb-md-0">
        <a href="{% url 'accounts:logout' %}" type="button" style = "margin-left: 10px"
          class="btn btn-outline-info btn-md btn-rounded btn-navbar waves-effect waves-light">Log Out</a>
      </li> 
    {% else %}
      <li class="nav-item">
        <a href="{% url 'accounts:login' %}" type="button" style = "margin-left: 10px"
          class="btn btn-outline-info btn-md btn-rounded btn-navbar waves-effect waves-light" >
          Sign in
        </a>
      </li>
      <tb></tb>
      <tb></tb>
      <li class="nav-item pl-2 mb-2 mb-md-0">
        <a href="{% url 'accounts:register' %}" type="button" style = "margin-left: 10px"
          class="btn btn-outline-info btn-md btn-rounded btn-navbar waves-effect waves-light">Sign up</a>
      </li>
  
  
    {% endif %}
         
            
        
      </ul>
      
    </ul>
  
        
        
    
  </div>
  <!-- Links -->
  
</nav>

ecom/store/templates/store/orders.html
{% extends 'store/main.html' %}
{% load static %}
{% load cartfilter %}
{% block content %}

<table class="table">
    <thead>
        <tr>
            <th>Sno.</th>
            <th>Image</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <div class="card"> 
            <tr>
                <td>{{forloop.counter}}</td>
                <td><img style="height: 80px;" class="rounded-circle" src="{{order.product.image.url}}" alt=""></td>
                <td>{{order.product.name}}</td>
                <td>{{order.price|currency}}</td>
                <td>{{order.quantity}}</td>
                <td>{{order.quantity|multiply:order.price|currency}}</td>
                {% if order.status %}
                    <td>{{order.status}}</td>
                
                {% endif %}
            </tr>
            
        </div>
  {% endfor %}

    </tbody>


</table>

{% endblock%}